services:
  redis:
    image: redis:8-alpine3.21
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true

  web:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    command: [ "./deploy.sh" ]
    ports:
      - "127.0.0.1:8000:8000" # Only bind to localhost for security

    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: [ "CMD", "python3", "./docker-health-check.py" ]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 240s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true

  celery_worker:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    command: >
      celery -A afinance worker --loglevel=info --concurrency=1 --prefetch-multiplier=1
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "celery -A afinance inspect ping -d celery@$${HOSTNAME} || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    security_opt:
      - no-new-privileges:true

  celery_beat:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    command: celery -A afinance beat -l info
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
    security_opt:
      - no-new-privileges:true

volumes:
  redis_data:
  logs_data:

    # docker pull acerschoolapp/acerschoolfinanceapp:latest && docker compose -f compose.prod.yaml up
