services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
      - logs_data:/var/log/nginx
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      - app_network

  redis:
    image: redis:8-alpine3.21
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    networks:
      - app_network

  web:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    command: [ "./deploy.sh" ]
    expose:
      - "8000"
    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: [ "CMD", "python3", "./docker-health-check.py" ]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 240s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      - app_network

  celery_worker:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    command: >
      celery -A afinance worker --loglevel=info --concurrency=4 --prefetch-multiplier=1
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "celery -A afinance inspect ping -d celery@$${HOSTNAME} || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    security_opt:
      - no-new-privileges:true
    networks:
      - app_network

  celery_beat:
    image: acerschoolapp/acerschoolfinanceapp:latest
    restart: unless-stopped
    command: celery -A afinance beat -l info
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
    security_opt:
      - no-new-privileges:true
    networks:
      - app_network

volumes:
  redis_data:
    driver: local
  logs_data:
    driver: local
  nginx_cache:
    driver: local

networks:
  app_network:
    driver: bridge
